### ISSUE TITLE
Move away from CocoaPods podspec format

### ISSUE THREAD

**Issue by kylef** [Conche/Conche#19]
To support custom entry_points and test_specification, we must roll our own specification format.

We should still allow using CocoaPods specifications, and depending on CocoaPod's but to use entry_points or test_specification a user must adopt the new format.

**Comment by orta** [comment]
IMO, it's worth shipping `cocoapods-test` just to not need to do this :P

**Comment by kylef** [comment]
@orta I'd have built `cocoapods-test` if I knew how to do it easily ;).

But I've also added `entry_points` to the format Conche uses to build CLI/Applications etc. Example:

CLI Tools:

```json
{
  "entry_points": {
    "cli": {
      "conche": "bin/conche"
    }
  }
}
```

OS X GUI Applications:


```json
{
  "entry_points": {
    "osx": "PLVAppDelegate"
  }
}
```

GTK, QT, linux etc:

```json
{
  "entry_points": {
    "gtk": "something something",
    "qt": "something something"
  }
}
```

So this really doesn't fit in the CocoaPods podspec format.

**Comment by kylef** [comment]
Closing out this issue as Conche is deprecated for the Swift Package Manager (SPM). Instead you can use SPM (https://github.com/Conche/Conche/commit/78708a9556b00d602de4c3e518a7f201b55a519b).
