### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by kylef** [Conche/Conche#7]
This depends on Swift becoming available for Linux.

**Comment by tadman** [comment]
[That day has come](https://developer.apple.com/swift/blog/?id=29), which is awesome.

**Comment by kylef** [comment]
Closing out this issue as Conche is deprecated for the Swift Package Manager (SPM). Instead you can use SPM (https://github.com/Conche/Conche/commit/78708a9556b00d602de4c3e518a7f201b55a519b).
